.gitignore
server/build.gradle
server/src/main/java/com/example/kakao_mlms/Sample.java
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/dto/response/UserDto.java
server/src/main/java/com/example/kakao_mlms/repository/UserRepository.java
server/src/main/java/com/example/kakao_mlms/service/UserService.java
server/src/main/resources/data.sql
server/src/test/java/com/example/kakao_mlms/controller/AdminControllerTest.java
server/src/test/java/com/example/kakao_mlms/repository/JpaRepositoryTest.java
server/src/test/java/com/example/kakao_mlms/service/UserServiceTest.java

[관리자] 회원 조회 리스트 구현

---

server/src/main/java/com/example/kakao_mlms/KakaoMlmsApplication.java
server/src/main/java/com/example/kakao_mlms/config/JpaConfig.java
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/domain/Answer.java
server/src/main/java/com/example/kakao_mlms/domain/Image.java
server/src/main/java/com/example/kakao_mlms/domain/Qna.java
server/src/main/java/com/example/kakao_mlms/domain/type/Category.java
server/src/main/java/com/example/kakao_mlms/domain/type/EQnaCategory.java
server/src/main/java/com/example/kakao_mlms/domain/type/Extension.java
server/src/main/java/com/example/kakao_mlms/dto/AnswerDto.java
server/src/main/java/com/example/kakao_mlms/dto/ImageDto.java
server/src/main/java/com/example/kakao_mlms/dto/QnaDto.java
server/src/main/java/com/example/kakao_mlms/dto/QnaDtoWithImages.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDetailDto.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaListDto.java
server/src/main/java/com/example/kakao_mlms/repository/AnswerRepository.java
server/src/main/java/com/example/kakao_mlms/repository/ImageRepository.java
server/src/main/java/com/example/kakao_mlms/repository/QnaRepository.java
server/src/main/java/com/example/kakao_mlms/service/QnaService.java
server/src/test/java/com/example/kakao_mlms/controller/AdminControllerTest.java
server/src/test/java/com/example/kakao_mlms/service/QnaServiceTest.java

> #16
> 관리자 Qna 조회 기능 추가
> PULL 받았을 때 QnaService, QnaRepository, Qna 엔티티에 충돌이 있어 모두 병합함

✨  관리자 QNA 조회 기능 추가

---

server/src/main/java/com/example/kakao_mlms/constant/Constants.java
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/controller/ImageController.java
server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
server/src/main/java/com/example/kakao_mlms/domain/Image.java
server/src/main/java/com/example/kakao_mlms/domain/Qna.java
server/src/main/java/com/example/kakao_mlms/domain/User.java
server/src/main/java/com/example/kakao_mlms/domain/type/Extension.java
server/src/main/java/com/example/kakao_mlms/dto/ImageDto.java
server/src/main/java/com/example/kakao_mlms/dto/QnaDto.java
server/src/main/java/com/example/kakao_mlms/dto/request/QnaRequestDto.java
server/src/main/java/com/example/kakao_mlms/dto/response/ImageResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoWithImagesResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/UserDto.java
server/src/main/java/com/example/kakao_mlms/intercepter/UserIdArgumentResolver.java
server/src/main/java/com/example/kakao_mlms/repository/QnaRepository.java
server/src/main/java/com/example/kakao_mlms/service/ImageService.java
server/src/main/java/com/example/kakao_mlms/service/QnaService.java
server/src/main/java/com/example/kakao_mlms/service/UserService.java
server/src/test/java/com/example/kakao_mlms/controller/AdminControllerTest.java
server/src/test/java/com/example/kakao_mlms/service/QnaServiceTest.java

회원 QNA 조회 기능, 회원 QNA 등록 기능
이미지 업로드, 다운로드 기능
Image 엔티티에 Category가 부모 엔티티인 QNA 엔티티의 Category와 겹쳐서 제외했어요

✨ [회원] QNA 등록 및 조회

---

server/src/main/java/com/example/kakao_mlms/constant/Constants.java
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/controller/ImageController.java
server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
server/src/main/java/com/example/kakao_mlms/domain/Image.java
server/src/main/java/com/example/kakao_mlms/domain/Qna.java
server/src/main/java/com/example/kakao_mlms/domain/User.java
server/src/main/java/com/example/kakao_mlms/domain/type/Extension.java
server/src/main/java/com/example/kakao_mlms/dto/ImageDto.java
server/src/main/java/com/example/kakao_mlms/dto/QnaDto.java
server/src/main/java/com/example/kakao_mlms/dto/request/QnaRequestDto.java
server/src/main/java/com/example/kakao_mlms/dto/response/ImageResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoWithImagesResponse.java
server/src/main/java/com/example/kakao_mlms/dto/response/UserDto.java
server/src/main/java/com/example/kakao_mlms/intercepter/UserIdArgumentResolver.java
server/src/main/java/com/example/kakao_mlms/repository/QnaRepository.java
server/src/main/java/com/example/kakao_mlms/service/ImageService.java
server/src/main/java/com/example/kakao_mlms/service/QnaService.java
server/src/main/java/com/example/kakao_mlms/service/UserService.java
server/src/test/java/com/example/kakao_mlms/controller/AdminControllerTest.java
server/src/test/java/com/example/kakao_mlms/service/QnaServiceTest.java

QNA 등록 시 이미지 파일이 필수 사항으로 되어 있어 빠르게 변경

✨ QNA 등록 시 이미지 파일 선택사항으로 변경

---

ai/src/data_processing/kakao_review_data_crawling.py

지난 번 작업했을때, 각각 리뷰어가 남긴 평점을 크롤링을 구현한줄 알았는데 누락되어있었음. 
데이터 크롤링에서 리뷰어 각각 남긴 평점을 크롤링 해온것을 추가. (100% 가 5.0을 의미함)
ex) 레벨2 | 1 | 5.0 | 100%; | 사장님이 지역 특산물로 만들어 주신 진도전복찜..특제 소스 콕 찍어 먹는 맛이 일품였어요.

✨ 리뷰어 각각 남긴 평점 크롤링 추가

---

server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
server/src/main/java/com/example/kakao_mlms/domain/Image.java
server/src/main/java/com/example/kakao_mlms/domain/Qna.java
server/src/main/java/com/example/kakao_mlms/domain/User.java
server/src/main/java/com/example/kakao_mlms/dto/QnaDto.java
server/src/main/java/com/example/kakao_mlms/dto/request/QnaRequestDto.java
server/src/main/java/com/example/kakao_mlms/service/ImageService.java
server/src/main/java/com/example/kakao_mlms/service/QnaService.java

> QNA 에서 게시글 수정 시 이미지도 반영되도록 수정
(현재는 수정 요청에 담긴 이미지 리스트를 통채로 기존의 이미지 리스트와 교환하는 방식인데 추후 고도화 작업을 한다면
해시 알고리즘을 사용하여 기존에 저장된 이미지와 비교 분석 후 변경점만 파악하여 반영하는 방식으로 개선 가능)

✨ QNA 수정 기능 (이미지 반영)

---

frontend/src/App.js
frontend/src/pages/Login.jsx
frontend/src/pages/SignUp.jsx
server/src/main/java/com/example/kakao_mlms/security/handler/signin/DefaultSignInSuccessHandler.java
server/src/main/resources/application.yml

> 프론트에서 버튼 클릭시 서버의 로그인과 소셜로그인, 회원가입 상호작용하도록 연동
> cors 에러 서버에서 nginx 통해 해결 예정

✨ 프론트 로그인 버튼 서버 통신 추가

---

ai/Dockerfile
jenkins/Dockerfile

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

젠킨스 도커 파일 수정

---

server/src/main/java/com/example/kakao_mlms/security/handler/signin/DefaultSignInSuccessHandler.java

> 로그인 성공 핸들러에서 매개 변수가 달라 생기는 오류 수정

🐛  로그인 핸들러 변수 오류 수정

---

frontend/src/components/user/LocationFinder.jsx

> front에서 server -> ai 통해서 식당 리뷰 분석 및 결과 출력 연동
> ai 에서 리뷰 분석하고 반환한 식당 리스트 출력하도록 연동했습니다.
> 조금만 양이 많아도 timeout 에러가 납니다....
> 디자인.....

✨ ai front review 분석 결과 연동

---

server/src/main/java/com/example/kakao_mlms/security/handler/signin/DefaultSignInSuccessHandler.java

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

fix: 응답에 nickname 한글 url인코딩 처리 후 전송

---

frontend/src/pages/user/QnaDetail.jsx
server/src/main/java/com/example/kakao_mlms/controller/QnaController.java

#65 , #66 
> #65 프론트 코드 수정
> #66 백엔드 코드 수정
> 비공개 게시글 접근 시도 시 status: 400, 존재하지 않는 게시글 접근 시도 시 status: 200으로 응답이 오는데, 프론트엔드에서 처리하기 복잡합니다. 상태 코드를 일관되게 통일하는 것이 필요합니다.
This closes #65 
This closes #66

🐛 Q&A 비공개 진입 불가 및 존재하지 않는 Q&A 상세 진입 시 Alert 미노출 현상 해결

---

frontend/src/components/user/LocationFinder.jsx
frontend/src/components/user/Map.jsx
frontend/src/components/user/StoreList.jsx
frontend/src/pages/user/Recommend.jsx

✨  ai 지도 최적화

---

frontend/src/pages/user/QnaDetail.jsx
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoWithImagesResponse.java

✨ 내 게시물이 아니면 수정, 삭제 버튼 비활성화

---

frontend/src/App.js
frontend/src/pages/user/QnaDetail.jsx
frontend/src/pages/user/SignUpKakao.jsx
server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
server/src/main/java/com/example/kakao_mlms/dto/response/QnaDtoWithImagesResponse.java

카카오 회원가입 후 닉네임 입력 페이지 구현 및 백엔드 연동
스프링 application.yml 에서
oauth2-success-guest: "https://shortood.shop-dev/sign-up-kakao"
이렇게 수정해주세요

✨ 카카오 회원가입 후 닉네임 입력 페이지 구현 및 백엔드 연동

---

frontend/src/pages/PageHeader.jsx
frontend/src/pages/admin/AdminQna.jsx
frontend/src/pages/admin/AdminQnaDetail.jsx
frontend/src/pages/admin/AdminUsers.jsx
server/src/main/java/com/example/kakao_mlms/exception/ErrorCode.java

> Admin에서 PageHeader 적용
> Q&A 상세 페이지에서 답변 작성 시 페이지 새로고침하지 않고 변경된 값 노출되도록 수정

🎨 프론트 관리자 코드 리팩토링

---

frontend/src/components/Api.jsx
frontend/src/pages/user/MyPage.jsx
frontend/src/pages/user/SignUp.jsx
frontend/src/pages/user/SignUpKakao.jsx
server/src/main/java/com/example/kakao_mlms/controller/AuthController.java
server/src/main/java/com/example/kakao_mlms/exception/ErrorCode.java
server/src/main/java/com/example/kakao_mlms/repository/UserRepository.java
server/src/main/java/com/example/kakao_mlms/service/AuthService.java

✨ 닉네임 중복 검사 로직 추가

---

ai/ai_server.py
ai/requirements.txt
ai/src/api/HDBSCAN_runner.py
ai/src/api/ensemble_ranking.py
ai/src/data_processing/kakao_review_data_crawling.py
ai/src/models/HDBSCAN_clustering.py

1. HDBSCAN을 활용한 리뷰 클러스터링 구축완료
2. 리턴하는 API 변경완료 및 api에 사용할만큼 적용하기위해 리팩토링 
3. 크롤링속도 향상을 위해 크롤링량 감소시킴 (5페이지->3페이지, 모든리뷰->멕시멈 약50개)
4.  클러스터링을 위한 requirements 추가
1. requirement 추가되었으니 서버에서 혹여나 오류나는지 확인
2. api 리턴하는것에 마지막에 클러스터링된 단어 5개 추가로 넘어가는 것으로 수정해야함, 리턴하는 가게 전부보내줬던걸 랭킹 상위 5개 하위 5개보내주는것으로 수정됨
3. 크롤링량 감소시켜서 응답 보통 1분에서 3분내로 들어옴

✨ HDBSCAN 활용한 클러스터링적용 및 크롤링량 조절로 모델속도 향상

---

frontend/src/components/user/LocationFinder.jsx
frontend/src/pages/user/Recommend.jsx

- 로그인 안하면 검색 불가능
- 검색 결과 병렬
- 데이터 있을때만 추천, 비추천 보이도록 수정

✨ 검색 페이지 수정

---

frontend/src/components/user/LocationFinder.jsx

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

✨ 검색 페이지 로그인 후 안되는거 수정

---

server/src/main/java/com/example/kakao_mlms/service/ReviewService.java

> 리뷰가 없는 경우 json이 안 맞아서 오류가는 것 처리
>

🐛 리뷰 blank인 경우 처리

---

frontend/src/components/user/Map.jsx

1. 받아오는 가게 목록을 기반으로 주소를 변환하여 가게에 마커를 찍음
>

✨  가게목록 마커 찍기 구현

---

ai/ai_server.py
ai/src/data_processing/kakao_review_data_crawling.py

1. "ranked_resturant" 안에 들어가던 주소 짤려서 앞부분 짤려서 들어가던 이슈 해결
2. "ranked_resturant" 의 개수가 10개 이하일 경우 중복으로 리턴되던것 수정완료

🐛 주소리턴값, 추천레스토랑 리턴개수 이슈해결

---

frontend/src/components/user/Map.jsx

✨  내 위치 별모양 마커 추가
